# Generated by Django 3.2.5 on 2023-04-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=200, verbose_name='班级名')),
                ('class_cate', models.IntegerField(blank=True, help_text='0 五天全日制 1 六天全日制 2预科班 3 周末班', null=True, verbose_name='班级分类')),
                ('start_time', models.DateTimeField(verbose_name='开班时间')),
                ('class_status', models.IntegerField(blank=True, help_text='0 正常 1禁用', null=True, verbose_name='班级状态')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '班级表',
                'db_table': 'basic_class',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=200, verbose_name='教室名')),
                ('room_count', models.IntegerField(blank=True, null=True, verbose_name='教室容量')),
                ('room_status', models.IntegerField(blank=True, default=0, help_text='0教室空闲 1教室禁用', null=True, verbose_name='教室状态')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '教室表',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=255, verbose_name='教师姓名')),
                ('teacher_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='教师工号')),
                ('teacher_level', models.IntegerField(verbose_name='教师等级')),
                ('sex', models.IntegerField(help_text='1 男 2 女', verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('phone', models.CharField(max_length=255, verbose_name='手机号')),
                ('birthday', models.CharField(blank=True, max_length=255, null=True, verbose_name='出生年月')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='教师邮箱')),
                ('school', models.CharField(blank=True, max_length=255, null=True, verbose_name='毕业院校')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='毕业院校院系')),
                ('major', models.CharField(blank=True, max_length=255, null=True, verbose_name='毕业院校专业')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='学历')),
            ],
            options={
                'verbose_name_plural': '老师表',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200, verbose_name='学生姓名')),
                ('add_time', models.DateTimeField(verbose_name='加入班级时间')),
                ('student_status', models.IntegerField(help_text='0正常 1 请假 2 休学 3 退学', verbose_name='学生状态')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('birthday', models.CharField(blank=True, max_length=200, null=True, verbose_name='出生年月日')),
                ('student_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱')),
                ('student_school', models.CharField(blank=True, max_length=200, null=True, verbose_name='院校')),
                ('student_department', models.CharField(blank=True, max_length=200, null=True, verbose_name='院系')),
                ('student_major', models.CharField(blank=True, max_length=200, null=True, verbose_name='专业')),
                ('student_school_class', models.CharField(blank=True, max_length=200, null=True, verbose_name='在校班级')),
                ('student_education', models.CharField(blank=True, max_length=200, null=True, verbose_name='学历')),
                ('phone', models.CharField(max_length=200, verbose_name='手机号')),
                ('qq_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='qq号')),
                ('wechart_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信号')),
                ('idcard', models.CharField(blank=True, max_length=200, null=True, verbose_name='身份证号')),
                ('emergency_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='紧急联系人姓名')),
                ('emergency_phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='紧急联系人电话')),
                ('family_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='家庭住址')),
                ('now_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='现在住址')),
                ('guarder', models.CharField(blank=True, max_length=200, null=True, verbose_name='监护人')),
                ('guarder_phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='监护人电话')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('Class', models.ManyToManyField(to='courseIndex.BasicClass', verbose_name='班级')),
            ],
            options={
                'verbose_name_plural': '学生表',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='CourseWeekData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(verbose_name='课表数据')),
                ('week', models.IntegerField(default=0, verbose_name='周数')),
                ('Section', models.IntegerField(verbose_name='节次')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseIndex.basicclass', verbose_name='班级')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseIndex.room', verbose_name='教室')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseIndex.teacher', verbose_name='老师')),
            ],
            options={
                'verbose_name_plural': '周课表数据',
                'db_table': 'course_weekdata',
            },
        ),
    ]
