# Generated by Django 3.2.5 on 2023-04-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseIndex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseweekdata',
            name='day',
            field=models.IntegerField(default=1, verbose_name='星期'),
            preserve_default=False,
        ),
    ]
