# Generated by Django 3.2.5 on 2023-04-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseIndex', '0002_courseweekdata_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseweekdata',
            name='data',
        ),
    ]
