# Generated by Django 3.2.5 on 2023-04-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseIndex', '0003_remove_courseweekdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseweekdata',
            name='subject',
            field=models.CharField(default='python', max_length=50, verbose_name='课程名'),
            preserve_default=False,
        ),
    ]
