# Generated by Django 3.2.5 on 2023-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseIndex', '0004_courseweekdata_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123456, max_length=200, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=123456, max_length=200, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
