# Generated by Django 3.2.5 on 2023-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseIndex', '0005_auto_20230409_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='学号'),
        ),
    ]
