# Generated by Django 3.2.5 on 2023-04-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseIndex', '0006_student_student_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_num',
            field=models.CharField(default='001', max_length=255, verbose_name='学号'),
            preserve_default=False,
        ),
    ]
